### ISSUE TITLE
Writing Process

### ISSUE THREAD

**Issue by janzeteachesit** [janzeteachesit/redefining-the-classroom#1]
Add to all writing repositories
- [x] GPhoto folder - 3s - [GPhotos - Medium - Start Here](https://goo.gl/photos/wzgYouZkAnM9GgBB6)
- [x] Search Medium for title - [Medium search query](https://medium.com/search?q=janzeteachesit)
- [ ] 3. Share via Gmail - GitHub and open
- [ ] 4. Clean up/link to GitHub issue
- [ ] 5. Writing template - issue or .md? 

GPhoto folders:
- [x] 3
- [x] 1
- [ ] done

[Writing GFolder](https://drive.google.com/open?id=0BxQaMnTJamWkfjU3VURSVS1lTHlJamh3Y0dTU3BpMmtQbVN2aEpmWEt2eXBoMVJnRk8xVXM) - requires sign-in
